package ie.lyit.app;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import javax.annotation.Generated;

/**
 * Interface generated by jhipster
 *
 * @author smallwindow21 team
 *
 */
@Generated(value = "JHipster", comments = "Generated by JHipster 7.0.1")
@Retention(RetentionPolicy.SOURCE)
@Target({ ElementType.TYPE })
public @interface GeneratedByJHipster {
}
