name: "SmallWindow21 Test Deploy"

on:
  push:
    branches: [ ! main ]

jobs:

  build-application:
    name: "Build Application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -B clean install --file app/pom.xml
      - run: mkdir test && cp app/target/smallwindow-21-0.0.1-SNAPSHOT.jar test
      - uses: actions/upload-artifact@v2
        with:
          name: TestPackage
          path: test
		  
	#different test actions
